### ISSUE TITLE
Getting 'Uncaught TypeError: Cannot read property 'replaceChild' of null' when using pie chart type

### ISSUE THREAD

**Issue by ng4123** [sheshbabu/react-frappe-charts#6] opened 2020-01-02 06:05 UTC
When I tried to embed the sample pie chart code provided in the project page into my React page component, the page would render for a split second, then crash with the following error stack (note that when using the other chart type like 'line', 'bar', it works fine, it only crashes when I switched to pie type), any idea what could cause this error?

Uncaught TypeError: Cannot read property 'replaceChild' of null
  | eval | @ | frappe-charts.min.esm.js?4215:1
-- | -- | -- | --
  | animateSVG | @ | frappe-charts.min.esm.js?4215:1
  | runSMILAnimation | @ | frappe-charts.min.esm.js?4215:1
  | value | @ | frappe-charts.min.esm.js?4215:1
  | value | @ | frappe-charts.min.esm.js?4215:1
  | eval | @ | frappe-charts.min.esm.js?4215:1
  | setTimeout (async) |   |  
  | value | @ | frappe-charts.min.esm.js?4215:1
  | value | @ | frappe-charts.min.esm.js?4215:1
  | e | @ | frappe-charts.min.esm.js?4215:1
  | getChartByType | @ | frappe-charts.min.esm.js?4215:1
  | t | @ | frappe-charts.min.esm.js?4215:1
  | eval | @ | index.js?8485:8
  | commitHookEffectList | @ | react-dom.development.js?61bb:22030
  | commitPassiveHookEffects | @ | react-dom.development.js?61bb:22064
  | callCallback | @ | react-dom.development.js?61bb:336
  | invokeGuardedCallbackDev | @ | react-dom.development.js?61bb:385
  | invokeGuardedCallback | @ | react-dom.development.js?61bb:440
  | flushPassiveEffectsImpl | @ | react-dom.development.js?61bb:25392
  | unstable_runWithPriority | @ | scheduler.development.js?3069:697
  | runWithPriority$2 | @ | react-dom.development.js?61bb:12149
  | flushPassiveEffects | @ | react-dom.development.js?61bb:25361
  | performSyncWorkOnRoot | @ | react-dom.development.js?61bb:24251
  | eval | @ | react-dom.development.js?61bb:12199
  | unstable_runWithPriority | @ | scheduler.development.js?3069:697
  | runWithPriority$2 | @ | react-dom.development.js?61bb:12149
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js?61bb:12194
  | flushSyncCallbackQueue | @ | react-dom.development.js?61bb:12182
  | unbatchedUpdates | @ | react-dom.development.js?61bb:24439
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js?61bb:27527
  | render | @ | react-dom.development.js?61bb:27608
  | eval | @ | index.jsx?ed12:21
  | ./src/index.jsx | @ | bundle.js:10803
  | __webpack_require__ | @ | bundle.js:20
  | 0 | @ | bundle.js:10852
  | __webpack_require__ | @ | bundle.js:20
  | (anonymous) | @ | bundle.js:84
  | (anonymous) | @ | bundle.js:87

**Comment by sheshbabu** [comment] 2020-01-02 12:02
Hi @ng4123, thanks for raising this. Are you able to reproduce this in a minimal create react app repo? 

This library is a very thin wrapper around frappe charts 😅

**Comment by ng4123** [comment] 2020-01-05 19:52
hi @sheshbabu , I tried to add the Frappe Chart component (pie type) to a simple create-react-app and it's giving me the same error, what I notice is it works as long as chart type is not 'pie' type. The version of NPM packages in my simple app, are you able to reproduce this issue yourself?

  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-frappe-charts": "^2.1.0",
    "react-scripts": "3.3.0"
  },

I'm using the sample code in the homepage:
function MyChart(props) {
  return (
    <ReactFrappeChart
      type="pie"
      colors={["#21ba45"]}
      axisOptions={{ xAxisMode: "tick", yAxisMode: "tick", xIsSeries: 1 }}
      height={250}
      data={{
        labels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        datasets: [{ values: [18, 40, 30, 35, 8, 52, 17, 4] }]
      }}
    />
  );
}

Stacktrace: 
Uncaught TypeError: Cannot read property 'replaceChild' of null
    at animation.js:81
    at Array.map (<anonymous>)
    at animateSVG (animation.js:72)
    at runSMILAnimation (animation.js:100)
    at e.value (BaseChart.js:246)
    at e.value (BaseChart.js:229)
    at index.js:17
    at commitHookEffectList (react-dom.development.js:22030)
    at commitPassiveHookEffects (react-dom.development.js:22064)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at flushPassiveEffectsImpl (react-dom.development.js:25392)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushPassiveEffects (react-dom.development.js:25361)
    at react-dom.development.js:25240
    at workLoop (scheduler.development.js:641)
    at flushWork (scheduler.development.js:596)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:203)

**Comment by albiesoft** [comment] 2020-02-29 18:59
I am having the same issue with the Pie chart

**Comment by CristianWesleyFront** [comment] 2020-02-29 20:00
I am having the same issue with the Pie chart + 1

**Comment by sheshbabu** [comment] 2020-04-15 10:37
@ng4123 @albiesoft @CristianWesleyFront Sorry for taking such a long time to respond. 

I was able to reproduce this when using `create-react-app` and the error didn't go away when upgrading to `frappe-charts@1.3.0`. 

However, it's just a dev mode error overlay, if you click the `x` at the top right or press ESC, this will go away. 

<img width="1062" alt="Screenshot 2020-04-15 at 6 36 31 PM" src="https://user-images.githubusercontent.com/498909/79328115-21395600-7f48-11ea-83c7-e4207fe11f69.png">

**Comment by sheshbabu** [comment] 2020-04-23 04:10
I'll close this issue, please let me know if there's a need to reopen it 🙂

**Closed by sheshbabu** 2020-04-23 04:10 UTC

**Comment by verzac** [comment] 2020-11-02 03:42
JFYI, I'm getting this error too on my pie chart, and it appears to be an issue with the original library's animation code. Issue happens for me pretty often too, and it causes my app (non-CRA, custom Webpack for WebExtension) to blank out (9/10 cases). Sure, I can "ignore" the error, but then I can't render the app and it spits out ugly console.errors.

Seems like it's something to do with the animation that Frappe is doing internally; it crashes because the parent container is null (when it's supposed to, you know, be there so that Frappe can do parent.replaceChild(...)).

It's probably a ref not getting passed in properly somewhere, and Frappe ends up hitting a null when trying to get the parent container. Since there doesn't seem to be any mention of this issue in the Frappe's main repo, I assume the root cause is here somewhere. I'll dig around and see if I can find the exact root cause, but if you don't hear from me, best assume that I've given up 😛.

Reference:
https://github.com/frappe/charts/blob/master/src/js/utils/animation.js (`runSMILAnimation` -> `animateSVG`)
https://github.com/frappe/charts/blob/master/src/js/charts/BaseChart.js (`this.container` is passed into `runSMILAnimation`)
